id: 9d4b8360-fd1e-11ec-b939-0242ac120002
label: s2_l2a_2025_07_01_region001
product:
  name: s2_l2a
crs: EPSG:4326
geometry:
  type: Polygon
  coordinates: [[[34.5, -1.0], [34.6, -1.0], [34.6, -1.1], [34.5, -1.1], [34.5, -1.0]]]
measurements:
  red: "C:/data/sentinel2_20250701_red.tif"
  nir: "C:/data/sentinel2_20250701_nir.tif"
  green: "C:/data/sentinel2_20250701_green.tif"
  blue: "C:/data/sentinel2_20250701_blue.tif"
properties:
  datetime: "2025-07-01T10:30:00Z"
  odc:processing_datetime: "2025-07-19T11:45:00Z"
  odc:file_format: GeoTIFF
