[server]
port = 8501
headless = true
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false  # Ajoute cette ligne !
[browser]
serverAddress = "localhost"
gatherUsageStats = false
