[server]
port = 8501
headless = false  # Permet l'ouverture automatique du navigateur
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false

[browser]
serverAddress = "localhost"  # Garde cette seule occurrence !
gatherUsageStats = false
serverPort = 8501
